// Generated by Wrangler on Fri Aug 09 2024 23:11:46 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	CACHE_CONTROLLER: "cache-tag.davidbarratt.workers.dev";
	API_TOKEN: string;
}
declare module "*.csv" {
	const value: string;
	export default value;
}
