// Generated by Wrangler on Fri Jul 26 2024 22:22:03 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	CACHE_CAPTURE: Queue;
}
declare module "*.csv" {
	const value: string;
	export default value;
}
