// Generated by Wrangler on Thu Jul 25 2024 23:03:56 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	CACHE_CAPTURE: Queue;
}
declare module "*.csv" {
	const value: string;
	export default value;
}
