// Generated by Wrangler on Sat Jul 27 2024 22:47:38 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env {}
